/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.BazaRegular;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Timax
 */
public class regularPanel extends javax.swing.JFrame {

    boolean bDalejPowrotButtonState = true;
    private BazaRegular db;

    public regularPanel() {
        initComponents();
        this.setLeftSide(false);
        this.setRightSide(false);
        this.bDalejWroc.setEnabled(false);
        this.bZarejestruj.setEnabled(false);
        db = new BazaRegular();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        kodSilnika = new javax.swing.JTextField();
        mocWKm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pojemnoscWCm3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        marka = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numerRejPojazdu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rodzajDoladowania = new javax.swing.JComboBox<>();
        wiek = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nazwisko = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        imie = new javax.swing.JTextField();
        zespol = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bDalejWroc = new javax.swing.JButton();
        bZarejestruj = new javax.swing.JButton();
        plec = new javax.swing.JComboBox<>();
        bNowyZawodnik = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mNowyZawodnik = new javax.swing.JMenuItem();
        mPanelAdministratora = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Kod silnika");

        jLabel2.setText("Moc (w KM)");

        jLabel3.setText("Rodzaj doładowania");

        jLabel4.setText("Pojemność (w cm3)");

        jLabel5.setText("Model");

        jLabel6.setText("Marka");

        jLabel7.setText("Numer Rejestracyjny");

        rodzajDoladowania.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "T", "C" }));

        jLabel9.setText("Wiek");

        jLabel11.setText("Płeć");

        jLabel12.setText("Nazwisko");

        jLabel13.setText("Imie");

        jLabel14.setText("Zespół (opc)");

        bDalejWroc.setText("Dalej");
        bDalejWroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDalejWrocActionPerformed(evt);
            }
        });

        bZarejestruj.setText("Zarejestruj");
        bZarejestruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZarejestrujActionPerformed(evt);
            }
        });

        plec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "K", "I" }));

        bNowyZawodnik.setText("Nowy Zawodnik");
        bNowyZawodnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNowyZawodnikActionPerformed(evt);
            }
        });

        statusLabel.setBackground(new java.awt.Color(255, 255, 255));
        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 51, 51));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Wybierz ,,Nowy zawodnik\" by rozpocząć");

        jMenu3.setText("Plik");

        mNowyZawodnik.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mNowyZawodnik.setText("Nowy zawodnik");
        mNowyZawodnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNowyZawodnikActionPerformed(evt);
            }
        });
        jMenu3.add(mNowyZawodnik);

        mPanelAdministratora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mPanelAdministratora.setText("Panel administratora");
        mPanelAdministratora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPanelAdministratoraActionPerformed(evt);
            }
        });
        jMenu3.add(mPanelAdministratora);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Pomoc");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNowyZawodnik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kodSilnika, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mocWKm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(marka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(numerRejPojazdu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rodzajDoladowania, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pojemnoscWCm3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(62, 62, 62)
                                .addComponent(nazwisko))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(bDalejWroc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(wiek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(zespol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(bZarejestruj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(plec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bNowyZawodnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(numerRejPojazdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(marka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pojemnoscWCm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(rodzajDoladowania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(plec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(wiek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(zespol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mocWKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodSilnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDalejWroc)
                    .addComponent(bZarejestruj)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNowyZawodnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNowyZawodnikActionPerformed
        this.setLeftSide(true);
        this.setRightSide(false);
        this.bDalejPowrotButtonState = true;
        this.bZarejestruj.setEnabled(false);
        this.bDalejWroc.setEnabled(true);
        this.bDalejWroc.setText("Dalej");
        this.resetFields();
        this.setStatus("Proszę wypełnić pola i nacisnąć [Dalej]");
    }//GEN-LAST:event_bNowyZawodnikActionPerformed

    private void bDalejWrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDalejWrocActionPerformed
        if (this.bDalejPowrotButtonState == true){
            this.setLeftSide(false);
            this.setRightSide(true);
            this.bDalejWroc.setText("Wroc");
            this.bZarejestruj.setEnabled(true);
            this.bDalejPowrotButtonState = false;
            this.setStatus("Proszę wypełnić pola i nacisnąć [Zarejestruj]");
        } else {
            this.setLeftSide(true);
            this.setRightSide(false);
            this.bDalejWroc.setText("Dalej");
            this.bZarejestruj.setEnabled(false);
            this.bDalejPowrotButtonState = true;
            this.setStatus("Proszę wypełnić pola i nacisnąć [Dalej]");
        }
    }//GEN-LAST:event_bDalejWrocActionPerformed

    private void bZarejestrujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZarejestrujActionPerformed
        this.setLeftSide(false);
        this.setRightSide(false);        
        this.bZarejestruj.setEnabled(false);
        this.bDalejWroc.setEnabled(false);
        try{
            this.db.dodajPojazdIZawodnika(numerRejPojazdu.getText(), marka.getText(), model.getText(), pojemnoscWCm3.getText(), rodzajDoladowania.getSelectedItem().toString(), mocWKm.getText(), kodSilnika.getText(), imie.getText(), nazwisko.getText(), plec.getSelectedItem().toString(), wiek.getText(), zespol.getText());  
            this.setStatus("Zarejestrowano pomyślnie");
        } catch (Exception e){
            this.setStatus(exceptionData(e.getClass().getSimpleName()));
        }
        //
        this.resetFields(); // <-ZAWSZE NA KOŃCU DAŁNIE BO POTEM SZUKASZ I SIE DZIWISZ
    }//GEN-LAST:event_bZarejestrujActionPerformed

    private String exceptionData (String data){
        if (data.contains("SQLServerException"))
                return "Błąd bazy danych, sprawdź połączenie i dane";
        else if (data.contains("NumberFormatException") || data.contains("string:"))
            return "Wprowadzono błędne dane";
        else
            return "Nieznany błąd: "+ data;
    }
    
    private void mNowyZawodnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNowyZawodnikActionPerformed
        this.bNowyZawodnikActionPerformed(evt);
    }//GEN-LAST:event_mNowyZawodnikActionPerformed

    private void mPanelAdministratoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPanelAdministratoraActionPerformed
        loggingPanel lp = new loggingPanel();
        lp.setTitle("R-Master");
        lp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        lp.setVisible(true);
    }//GEN-LAST:event_mPanelAdministratoraActionPerformed

    private void setStatus(String status){
        this.statusLabel.setText(status);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regularPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regularPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regularPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regularPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regularPanel().setVisible(true);
            }
        });
    }
    
    private void setLeftSide (boolean state){
        this.numerRejPojazdu.setEnabled(state);
        this.marka.setEnabled(state);
        this.model.setEnabled(state);
        this.pojemnoscWCm3.setEnabled(state);
        this.rodzajDoladowania.setEnabled(state);
        this.mocWKm.setEnabled(state);
        this.kodSilnika.setEnabled(state);
    }
    
    private void setRightSide (boolean state){
        this.imie.setEnabled(state);
        this.nazwisko.setEnabled(state);
        this.plec.setEnabled(state);
        this.wiek.setEnabled(state);
        this.zespol.setEnabled(state);
    }
    
    private void resetFields () {
        this.numerRejPojazdu.setText(null);
        this.marka.setText(null);
        this.model.setText(null);
        this.pojemnoscWCm3.setText(null);
        this.rodzajDoladowania.setSelectedItem('N');
        this.mocWKm.setText(null);
        this.kodSilnika.setText(null);
        this.imie.setText(null);
        this.nazwisko.setText(null);
        this.plec.setSelectedItem('M');
        this.wiek.setText(null);
        this.zespol.setText(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDalejWroc;
    private javax.swing.JButton bNowyZawodnik;
    private javax.swing.JButton bZarejestruj;
    private javax.swing.JTextField imie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JTextField kodSilnika;
    private javax.swing.JMenuItem mNowyZawodnik;
    private javax.swing.JMenuItem mPanelAdministratora;
    private javax.swing.JTextField marka;
    private javax.swing.JTextField mocWKm;
    private javax.swing.JTextField model;
    private javax.swing.JTextField nazwisko;
    private javax.swing.JTextField numerRejPojazdu;
    private javax.swing.JComboBox<String> plec;
    private javax.swing.JTextField pojemnoscWCm3;
    private javax.swing.JComboBox<String> rodzajDoladowania;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField wiek;
    private javax.swing.JTextField zespol;
    // End of variables declaration//GEN-END:variables
    
}
